"""Seed a realistic synthetic oil-company knowledge base for RAG demos.

Usage:
    python backend/seed_oil_kb.py
    python backend/seed_oil_kb.py --org-id indianoil-demo
    python backend/seed_oil_kb.py --org-id indianoil-demo --resume

The records are explicitly synthetic. They use an Indian-oil-company-style
operating model without representing any real company's confidential data.
The script is idempotent for its own ``[SYNTHETIC OIL DEMO]`` documents and
ingests through data.service.ingest_doc so chunks receive real vectors.
"""
import argparse
import os
import sys
from dataclasses import dataclass

from dotenv import load_dotenv

ROOT = os.path.dirname(os.path.dirname(__file__))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)
load_dotenv(os.path.join(ROOT, ".env"))

from data.db import get_conn
from data.service import ingest_doc


ORG_NAME = "Indian Oil Demo Operations"
TITLE_PREFIX = "[SYNTHETIC OIL DEMO]"


@dataclass(frozen=True)
class Record:
    category: str
    title: str
    owner: str
    zone: str
    asset: str
    keywords: str
    details: str


def _r(category, title, owner, zone, asset, keywords, details):
    return Record(category, title, owner, zone, asset, keywords, details)


# The metadata is deliberately repeated in the document body so both keyword
# and vector retrieval can find it. The catalog is expanded below into 300
# distinct documents for one organisation.
RECORDS = [
    # Organization, zones, ownership, and contacts.
    _r("organization", "Zone A operating model", "Asha Menon, Area Manager", "Zone A", "Crude receipt and tank farm", "Zone A ownership manager escalation", "Zone A receives imported and domestic crude, performs custody transfer, and stores feedstock in TK-101 through TK-106. The Area Manager owns production coordination. Shift Supervisor Ravi Kumar controls the field handover. Mechanical maintenance is led by Neha Singh; electrical and instrumentation are led by Joseph Thomas. Operations Control Room extension 210 is the first escalation point. The zone boundary runs from the inlet manifold through tank farm outlet block valves and ends at the crude dispatch battery limit. Any work crossing that boundary requires coordination with the central control room."),
    _r("organization", "Zone B operating model", "Bhavesh Rao, Area Manager", "Zone B", "Primary distillation unit", "Zone B ownership CDU distillation manager", "Zone B operates the atmospheric distillation unit and associated desalter, furnace, overhead condenser, and side-stripper systems. The Area Manager owns throughput and stable operation. The panel operator controls setpoints from DCS, while the field operator verifies local valves, pumps, and leaks. Mechanical lead Neha Singh owns rotating equipment; process engineer Kavita Iyer owns operating envelopes. The zone battery limit starts at the crude preheat train inlet and ends at the atmospheric residue outlet. CDU alarms are acknowledged by the panel operator and escalated to the Shift Supervisor if not recovered within ten minutes."),
    _r("organization", "Zone C operating model", "Charu Nair, Area Manager", "Zone C", "L09 and L10 pipeline corridor", "Zone C L09 L10 pipeline pressure ownership", "Zone C manages the L09 and L10 transfer pipeline corridor, pump stations PS-09 and PS-10, block valve stations BV-09A and BV-10A, and the local metering skid. Charu Nair is the Area Manager. The pipeline controller owns flow authorization and line-up confirmation. Field operator Imran Sheikh performs route inspection. Mechanical lead Neha Singh owns pumps and valves, and instrumentation lead Joseph Thomas owns pressure transmitters and flow meters. Normal L09 operating pressure is 3.5 to 5.5 bar. A pressure above 6.0 bar requires immediate rate reduction and Shift Supervisor notification."),
    _r("organization", "Zone D operating model", "Devika Shah, Area Manager", "Zone D", "Product blending and dispatch", "Zone D blending dispatch ownership gasoline diesel", "Zone D blends gasoline, diesel, and aviation turbine fuel and dispatches finished products by road tanker and pipeline. The Area Manager owns schedule adherence and product segregation. The laboratory supervisor releases batches; the loading supervisor owns truck bay safety and documentation. Tanks TK-201 through TK-208 are product-specific and must not be cross-connected without a written line-up. The dispatch battery limit includes additive injection, loading arms, grounding monitors, and gate documentation. Any off-specification result blocks dispatch until Quality and Operations jointly disposition the batch."),
    _r("organization", "Zone E utilities operating model", "Eshan Verma, Area Manager", "Zone E", "Boiler house and cooling water", "Zone E utilities boiler cooling water ownership", "Zone E supplies steam, cooling water, instrument air, nitrogen, and electrical distribution. The Area Manager owns utility reliability. Boiler operator Priya Das controls combustion and drum level. Utilities mechanical lead owns boiler feed pumps and cooling tower fans. Electrical lead owns switchgear and emergency power. Minimum instrument-air header pressure is 5.5 barg; below 5.0 barg, nonessential pneumatic users are isolated. Cooling water return temperature above 38 C requires load review. Utilities changes affecting production must be communicated to every area control room before implementation."),
    _r("organization", "Central control room responsibilities", "Sanjay Kulkarni, Operations Superintendent", "All zones", "Central control room", "control room roles alarm response shift handover", "The central control room maintains the plant operating picture, approves major line-ups, coordinates simultaneous operations, and records abnormal events. The panel operator owns DCS alarm response; the field operator owns physical verification; the Shift Supervisor owns cross-zone decisions. Critical alarms are acknowledged immediately and investigated within five minutes. The minimum shift handover includes plant status, active permits, bypassed trips, isolated equipment, tank levels, quality holds, environmental deviations, and open incident actions. Handover is verbal and written; the incoming supervisor signs the electronic log before taking control."),
    _r("organization", "Maintenance ownership matrix", "Neha Singh, Maintenance Manager", "All zones", "Mechanical, electrical, instrumentation", "maintenance owner RACI work order priority", "Maintenance uses a RACI model. Operations is responsible for safe isolation and equipment handback; Maintenance is responsible for execution quality; Reliability Engineering is accountable for criticality and bad-actor analysis; HSE is consulted for hazardous work; the Area Manager is informed of schedule risk. Priority 1 work addresses an immediate safety or containment threat. Priority 2 work addresses degraded production or protection. Priority 3 work is planned backlog. No work order may be closed until guards are restored, tools are removed, test results are attached, and Operations accepts the equipment."),
    _r("organization", "Emergency response command structure", "Meera Joshi, Emergency Director", "All zones", "Incident command system", "emergency roles incident commander muster control room", "During a plant emergency, the Incident Commander has overall authority. The Zone Controller manages the affected area, the Emergency Response Team controls rescue and fire response, and the Control Room maintains process stabilization. The Muster Coordinator accounts for personnel and contractors. Security controls access and emergency gates. The Medical Coordinator manages first aid and ambulance interface. Any employee may raise an alarm. Communications must state location, material, observed condition, injured persons, and safe access route. Re-entry is prohibited until the Incident Commander gives an all-clear."),
    _r("organization", "Contractor governance and onboarding", "Leena Kapoor, Contracts and HSE Lead", "All zones", "Contractor work fronts", "contractor induction permit competency onboarding", "Contractors must complete site induction, task competency verification, medical fitness checks where required, and zone-specific orientation before receiving access. The contractor supervisor owns crew behavior and attendance. The BigBrain site register must not be treated as a substitute for the permit system. Contractor personnel follow the same isolation, PPE, confined-space, work-at-height, and emergency rules as employees. Daily toolbox talks record task, hazards, controls, weather, simultaneous operations, and names. Repeated permit deviations trigger stop-work and a management review."),
    _r("organization", "Document control and records retention", "Nitin Bose, Document Controller", "All zones", "Controlled procedures repository", "document control revision obsolete copy retention", "Controlled procedures carry an owner, approver, revision, effective date, review date, and superseded-document reference. Printed controlled copies are stamped and listed by location. Uncontrolled copies are for reference only and must not be used for field execution. Operations records retain shift logs, inspection sheets, calibration certificates, laboratory results, permits, and incident actions according to the corporate retention schedule. A procedure change requires impact review for training, MOC, spares, alarms, and drawings. The current effective revision is the only approved basis for work."),

    # Process and equipment SOPs.
    _r("sop", "SOP for starting crude transfer pump P-201", "Ravi Kumar, Shift Supervisor", "Zone A", "P-201 crude transfer pump", "P-201 start up SOP crude pump suction discharge", "Before starting P-201, confirm the approved transfer plan, tank level, suction valve open position, discharge route, destination capacity, and communication with the receiving zone. Verify seal flush, bearing oil level, coupling guard, local emergency stop reset, and no active maintenance tag. Open suction fully, crack discharge as required by the start-up sheet, and confirm minimum-flow recirculation available. Start from the local panel only after the control room grants permission. Confirm discharge pressure, motor current, vibration, seal leakage, and flow within five minutes. Stop if pressure fails to build, vibration rises, or seal leakage is visible. Record start time and readings in the shift log."),
    _r("sop", "SOP for CDU normal shutdown", "Kavita Iyer, Process Engineer", "Zone B", "Crude distillation unit", "CDU shutdown procedure furnace desalter column", "For a planned CDU shutdown, reduce feed gradually according to the approved rate ramp, stabilize furnace outlet temperature, reduce stripping steam, and confirm downstream receiving capacity. Stop crude feed only after the control room confirms the line-up. Maintain circulation and cooling as defined by the shutdown sheet. Depressurize only through approved systems; never vent hydrocarbons to atmosphere. Monitor column pressure, overhead temperature, accumulator level, furnace draft, and residue outlet temperature. Isolate and drain equipment only under a permit and isolation certificate. The Shift Supervisor confirms the unit is in a safe state before maintenance releases equipment."),
    _r("sop", "SOP for pipeline line-up and transfer", "Imran Sheikh, Pipeline Controller", "Zone C", "L09 transfer pipeline", "L09 line up transfer valve checklist", "The L09 line-up requires two-person verification. The controller reads the approved transfer order; the field operator physically identifies each valve by tag and position. Confirm source tank, destination tank, route, block valves, drains closed, vents closed, pig trap status, meter availability, and communication with both ends. Record initial pressure and temperature. Start at low flow and hold for five minutes while checking pressure response and route inspection. Increase to the approved rate only after no leak, abnormal pressure rise, or unexpected level movement is found. Stop transfer for a pressure deviation, loss of communication, spill, or wrong-route indication."),
    _r("sop", "SOP for crude tank receipt", "Asha Menon, Area Manager", "Zone A", "TK-101 through TK-106", "crude tank receipt level ullage water draw", "Before crude receipt, verify tank availability, working volume, roof or vent condition, high-level alarm, independent level gauge, inlet route, and water draw status. Calculate the expected final level and keep the high-high alarm margin. Take a representative pre-receipt sample when required. Start receipt at the low initial rate and compare observed level rise to expected volume. Check tank shell, bund, valve manifold, and vapor control for leaks. During receipt, record level, temperature, pressure, flow, and sample status at the shift frequency. Stop before the alarm setpoint and obtain supervisor approval for any deviation from the approved receiving plan."),
    _r("sop", "SOP for product blending and recipe change", "Sonal Mehta, Blending Supervisor", "Zone D", "Blending skid BS-02", "blending recipe change gasoline diesel batch", "Only the released recipe in the production planning system may be used. Before a recipe change, complete a line-clearance check, flush or drain incompatible residual product, verify additive tank identity, and confirm meter calibration status. The panel operator reads the recipe aloud and the field operator verifies valve and hose tags. Start the first component at low rate and confirm meter response. Record component totals and additive injection rate. A recipe change during an active batch requires supervisor approval and a new batch record. If any component total, density, or additive rate is outside the recipe tolerance, stop addition and place the batch on quality hold."),
    _r("sop", "SOP for boiler light-off", "Priya Das, Utilities Supervisor", "Zone E", "Boiler B-01", "boiler light off purge fuel gas drum level", "Before light-off, verify the boiler is released from maintenance, all personnel are clear, fuel gas pressure is available, burner management system healthy, flame scanner operational, drum level normal, and feedwater available. Complete the mandatory furnace purge for the duration and airflow specified by the approved burner management procedure. Never bypass purge, flame failure, or low-low drum protection. Open fuel only after the permissive is present. Observe flame stability, furnace draft, steam pressure rise, and drum level. If flame is lost, shut fuel, complete the required re-purge, and investigate before another attempt. Record each permissive and operator confirmation in the boiler log."),
    _r("sop", "SOP for cooling tower fan changeover", "Vikram Rao, Utilities Engineer", "Zone E", "Cooling tower CT-03", "cooling tower fan changeover vibration temperature", "Check the standby fan, gearbox oil, coupling guard, local controls, vibration switch, and electrical supply before changeover. Confirm the running fan can be unloaded without exceeding cooling-water return temperature. Start the standby fan locally or from DCS according to the approved line-up, verify rotation, and compare motor current and vibration. Allow the standby fan to stabilize before stopping the duty fan. Record supply temperature, return temperature, fan current, vibration, and basin level. If both fans trip, notify the control room and reduce process loads that depend on cooling water. Do not enter the fan deck without a task-specific permit."),
    _r("sop", "SOP for loading road tankers", "Farah Khan, Loading Supervisor", "Zone D", "Road tanker loading bays", "road tanker loading grounding overfill checklist", "The loading supervisor verifies vehicle authorization, product compartment certificate, driver induction, wheel chocks, bonding and grounding, emergency stop availability, loading arm condition, and correct bay assignment. Confirm product name and quantity against the dispatch document before opening the loading valve. Grounding permissive must remain healthy throughout loading. Start slowly, watch for leaks and overfill alarm status, then load at the approved rate. Close valves before disconnecting arms, cap connections, remove grounding last, and complete seal and document checks. Any grounding failure, vapor alarm, spill, wrong product, or overfill alarm requires immediate stop and supervisor response."),
    _r("sop", "SOP for nitrogen inerting", "Joseph Thomas, Instrumentation Lead", "Zone A", "Nitrogen header and vessels", "nitrogen inerting oxygen concentration confined space", "Nitrogen inerting is permitted only under an approved procedure and isolation plan. Confirm the vessel boundary, vent destination, oxygen monitoring, nitrogen source pressure, non-return valves, and warning barricades. Establish an exclusion zone because nitrogen can displace breathable air without visible warning. Introduce nitrogen at the controlled rate and monitor oxygen at the required sampling points. Do not enter an inerted or suspected inerted space. Before opening equipment for personnel, isolate nitrogen, ventilate, test oxygen and toxic gases, and issue the confined-space permit. Record start and stop times, oxygen readings, operator names, and valve line-up."),
    _r("sop", "SOP for shift handover and field rounds", "Sanjay Kulkarni, Operations Superintendent", "All zones", "Shift log and field rounds", "shift handover checklist field operator rounds", "The outgoing shift prepares a written handover before the face-to-face briefing. It includes running equipment, abnormal conditions, alarms, bypasses, permits, isolations, tank movements, quality holds, environmental readings, maintenance status, and expected changes. The incoming shift repeats critical information and asks questions before accepting control. Field rounds follow the zone route and check pressure, temperature, levels, vibration, leaks, unusual noise, housekeeping, fire equipment access, and valve positions. Missed rounds are recorded with reason and supervisor action. The electronic log is signed by both supervisors; verbal-only handover is not acceptable for a controlled process."),

    # Safety and emergency procedures.
    _r("safety", "Hydrocarbon spill response guideline", "Meera Joshi, HSE Manager", "All zones", "Spill response equipment", "hydrocarbon spill response isolate source foam drain", "On discovering a hydrocarbon spill, raise the alarm, stop the source if safe, remove ignition sources, and keep people upwind. Do not walk through the liquid or operate equipment that may create a spark. Protect drains with spill kits and close remote isolation valves when authorized. The Zone Controller establishes the hot, warm, and cold boundaries. Trained responders use the correct PPE and absorbent or containment boom. Notify the control room, HSE, and Incident Commander with location, estimated quantity, product, drain impact, and injuries. Recovery, waste labeling, cause investigation, and area release are documented before normal operation resumes."),
    _r("safety", "Hydrogen sulfide awareness and response", "Meera Joshi, HSE Manager", "Zones A and B", "H2S monitoring network", "H2S alarm response breathing apparatus muster", "Hydrogen sulfide may be present in crude and sour streams. Odor is not a reliable warning because smell fatigue occurs quickly. Personnel wear the required personal monitor in designated areas and verify escape routes before work. On an H2S alarm, stop work, move crosswind and then upwind to the assigned muster point, warn others without entering the release, and report to the Zone Controller. Only trained responders with appropriate respiratory protection may approach the source. The control room isolates or depressurizes according to the emergency procedure. Re-entry requires gas-test results, Incident Commander approval, and a communicated all-clear."),
    _r("safety", "Confined-space entry standard", "Leena Kapoor, HSE Lead", "All zones", "Tanks, pits, vessels, and sewers", "confined space entry permit gas test attendant rescue", "A confined space entry requires hazard identification, isolation certificate, cleaning verification, atmospheric test, permit approval, attendant, rescue plan, communication method, and entry log. Initial testing covers oxygen, flammability, and toxic gases relevant to the service. Continuous monitoring is required when conditions can change. The attendant remains outside and does not perform another task. Ventilation must not introduce a new hazard. Entrants exit immediately on alarm, communication loss, symptom, ventilation failure, or change in conditions. Rescue is performed by a trained team; unplanned entry to rescue a colleague is prohibited. The permit is closed only after all personnel are accounted for."),
    _r("safety", "Hot work permit requirements", "Leena Kapoor, HSE Lead", "All zones", "Welding, cutting, and grinding", "hot work permit gas test fire watch spark containment", "Hot work requires a permit, equipment isolation, gas testing, removal or shielding of combustibles, fire extinguishers, spark containment, and a trained fire watch. The permit issuer confirms the work boundary and adjacent levels, drains, vents, and equipment. Gas testing is completed before work and repeated at the frequency defined by the permit or whenever conditions change. Fire watch remains during the work and for the post-work monitoring period. Hot work stops for any flammable-gas alarm, loss of ventilation, changed wind direction, nearby hydrocarbon release, or failure of fire protection. Permit copies remain at the job and in the control room."),
    _r("safety", "Lockout and tagout isolation standard", "Neha Singh, Maintenance Manager", "All zones", "Energy isolation points", "LOTO isolation try test zero energy", "The authorized isolating person identifies every energy source: electrical, hydraulic, pneumatic, mechanical, thermal, chemical, pressure, and stored energy. The isolation plan lists valves, breakers, blinds, drains, vents, and locks by tag. After isolation, trapped pressure is released and zero energy is verified by a try test or approved measurement. Each worker applies a personal lock where the system requires group isolation. The equipment owner and permit issuer independently verify the boundary. Removing a lock requires the owner or the formal absent-person process. Re-energization follows a clearance check, guard restoration, personnel count, communication, and controlled return to service."),
    _r("safety", "Work at height and dropped-object prevention", "Leena Kapoor, HSE Lead", "All zones", "Structures, pipe racks, and platforms", "work at height harness dropped object tool tether", "Work at height requires a suitable platform or scaffold, inspection tag, edge protection, access control, and fall-arrest equipment where required. Workers inspect harnesses, lanyards, anchor points, and tools before use. Tools and materials are secured against falling. The area below is barricaded and no person passes through the drop zone. Ladders are for short-duration access only and must be secured. Wind, rain, poor visibility, or an unsafe platform stops the work. Rescue arrangements are confirmed before starting because suspension trauma can develop quickly. The supervisor records the pre-job briefing and verifies housekeeping at completion."),
    _r("safety", "Electrical safety and arc-flash boundary", "Joseph Thomas, Electrical Lead", "All zones", "Switchgear and MCC rooms", "electrical isolation arc flash PPE test before touch", "Only authorized electrical personnel may open switchgear or perform electrical work. The job plan identifies voltage, arc-flash boundary, shock boundary, isolation point, backfeed risk, and required PPE. Before touching conductors, isolate, lock, tag, prove the tester, test for absence of voltage, and re-prove the tester. Doors and covers remain closed during normal operation. Water, loose metal, and unauthorized storage are prohibited in electrical rooms. An electrical fire is not attacked with water. Any trip, burning smell, hot connection, or damaged cable is reported immediately and the affected equipment is kept out of service until assessed."),
    _r("safety", "Process alarm response priorities", "Sanjay Kulkarni, Operations Superintendent", "All zones", "DCS and safety instrumented alarms", "alarm priority critical high response acknowledgement", "Alarm priority is based on consequence and time to respond, not on how often it sounds. Critical alarms require immediate acknowledgement, physical or process verification, and control action according to the alarm response sheet. High alarms require action within the stated response time. Nuisance alarms are not suppressed informally; the operator logs the condition and the instrument team investigates. Alarm shelving needs a reason, owner, expiry, and compensating measure. Bypasses of trips and interlocks require authorization and a visible register. The shift supervisor reviews standing alarms at each handover and assigns unresolved alarms an action."),
    _r("safety", "Emergency depressurization guideline", "Meera Joshi, Emergency Director", "Zones B and C", "Emergency flare and blowdown system", "emergency depressurization flare blowdown decision", "Emergency depressurization is a controlled action used when escalation risk exceeds the hazards of sending material to the flare system. The Incident Commander or authorized Shift Supervisor confirms affected equipment, flare capacity, personnel status, isolation options, and downstream effects. The control room announces the action and records time, valves, pressure, and reason. Field personnel move to safe locations and avoid low areas or downwind routes. Depressurization does not replace source isolation or fire response. Operators monitor flare header pressure, knockout drum level, radiation boundaries, and neighboring zones. Any abnormal flare behavior is reported immediately and the event receives a post-incident review."),
    _r("safety", "Muster and personnel accountability", "Farah Khan, Muster Coordinator", "All zones", "Muster points and access gates", "muster roll call contractor accountability emergency", "Each zone has a primary and alternate muster point selected for wind, access, and process hazards. On alarm, employees and contractors stop work, take no shortcuts through process areas, and report to the assigned point. Supervisors bring current attendance lists and identify missing persons, last known location, and task. Security provides gate and visitor records. The Muster Coordinator sends one consolidated count to the Incident Commander; duplicate reports are avoided. No one leaves the muster point without authorization. A drill is treated as real for accountability purposes, but the alarm announcement states when a drill is in progress."),

    # Maintenance and reliability.
    _r("maintenance", "P-204 preventive maintenance standard", "Neha Singh, Maintenance Manager", "Zone C", "P-204 transfer pump", "P-204 inspection interval preventive maintenance vibration", "P-204 receives a field inspection every shift, a detailed mechanical inspection every month, and a planned preventive maintenance intervention every six months unless reliability data requires an earlier task. The shift inspection checks seal leakage, bearing temperature, vibration, unusual noise, coupling guard, oil level, and discharge pressure. Monthly work includes alignment review, baseplate and anchor inspection, lubrication condition, and instrument comparison. A vibration trend above the alert limit is reviewed by Reliability Engineering; a rapid increase, rising bearing temperature, or visible seal failure requires controlled shutdown. Maintenance history, parts used, measurements, and return-to-service test results are attached to the work order."),
    _r("maintenance", "Rotating equipment lubrication guideline", "Neha Singh, Maintenance Manager", "All zones", "Pumps, compressors, and fans", "lubrication oil grease contamination interval", "Lubrication intervals follow the equipment register, lubricant manufacturer compatibility, operating temperature, and condition-monitoring results. Operators do not mix oils or greases without Maintenance approval. Before adding lubricant, clean the fitting, verify the correct product and quantity, and inspect for blocked breathers or leaks. Over-greasing can raise bearing temperature and damage seals. Used oil samples are labeled with equipment tag, date, running hours, and sampler. Water ingress, metal particles, burnt smell, or unexpected viscosity triggers a reliability review. The lubrication route records missed points and reasons; a green mark without a measured or observed task is not an acceptable record."),
    _r("maintenance", "Valve inspection and stroking program", "Neha Singh, Maintenance Manager", "Zones A and C", "Block and control valves", "valve stroking inspection block valve leak passing", "Critical block valves are identified in the isolation register and inspected for tag legibility, access, position indication, packing leakage, handwheel condition, and support. Functional stroking is scheduled only when the process line-up allows it and Operations approves the risk. Control valves are checked for travel, response, air supply, fail position, and positioner health. A valve that does not reach its commanded position is treated as unavailable until repaired or formally risk-assessed. Passing isolation, leakage, seized stem, or damaged actuator findings receive a work order and are cross-referenced to the affected SOP and emergency isolation plan."),
    _r("maintenance", "Pressure safety valve management", "Joseph Thomas, Instrumentation Lead", "All zones", "PSVs and rupture protection", "PSV set pressure inspection test certificate relief valve", "Every pressure safety valve has a unique tag, protected service description, set pressure, inlet and outlet size, discharge destination, last test date, next due date, and certificate. The relief path must not be isolated during operation unless an approved engineered protection is in place. Removal requires a permit, isolation, depressurization, and a temporary protection review. Bench testing records pop pressure, blowdown, seat leakage, condition, repairs, and seal status. A PSV lift, simmer, blocked discharge, or damaged seal is reported to the Shift Supervisor and Reliability Engineering. The register is reviewed monthly for overdue tests and inaccessible valves."),
    _r("maintenance", "Instrument calibration management", "Joseph Thomas, Instrumentation Lead", "All zones", "Pressure, temperature, flow, and level instruments", "instrument calibration transmitter calibration due date", "Critical instruments have a calibration interval based on service risk, drift history, manufacturer guidance, and protection function. Calibration uses traceable standards and records as-found and as-left readings, range, units, test points, error, technician, date, and certificate number. A failed as-found result triggers an impact assessment for product quality, safety trips, and historical data. Instruments in bypass or degraded service are listed in the control room register with compensating measures. After calibration, the operator confirms DCS indication, alarm setpoints, engineering units, and trend behavior. Calibration stickers do not replace the electronic certificate."),
    _r("maintenance", "Heat exchanger fouling monitoring", "Kavita Iyer, Process Engineer", "Zone B", "Preheat train exchangers", "heat exchanger fouling delta T pressure drop cleaning", "The preheat train is monitored using inlet and outlet temperatures, flow, pressure drop, and furnace duty. Fouling is suspected when temperature approach deteriorates while flow and feed quality remain comparable, or when pressure drop increases beyond the operating baseline. Operators record daily indicators and Process Engineering reviews the trend weekly. Cleaning requires a shutdown or approved online method, isolation, draining, and environmental controls for hydrocarbon residue. After cleaning, record restored duty and pressure drop to establish a new baseline. A rapid performance decline can indicate corrosion, tube leakage, wrong line-up, or instrumentation error and must not be attributed to fouling without checks."),
    _r("maintenance", "Corrosion monitoring circuit plan", "Mohan Iyer, Reliability Engineer", "Zones A and C", "Crude and transfer piping", "corrosion monitoring thickness UT inspection circuit", "Corrosion circuits group piping and equipment exposed to similar fluid, temperature, velocity, and metallurgy. Thickness measurement points are marked on isometrics and tagged in the inspection system. The inspector records location, method, calibration, nominal thickness, previous thickness, current thickness, and calculated rate. Rates use comparable readings and are reviewed for measurement uncertainty. Localized pitting, under-insulation corrosion, dead-leg corrosion, or rapid loss is escalated immediately. Engineering sets inspection intervals and remaining-life actions. Coating repair, chemical treatment, drainage improvement, and operating changes are tracked as separate actions; repainting alone does not close an active corrosion mechanism."),
    _r("maintenance", "Tank inspection and integrity schedule", "Mohan Iyer, Reliability Engineer", "Zone A", "Crude and product storage tanks", "tank inspection floor shell roof settlement integrity", "Storage tanks are inspected according to service, age, code requirements, and risk ranking. Routine external rounds check shell, roof, vents, stairs, nozzles, foundation, settlement markers, bund, valves, and signs of leakage. Internal inspection checks floor, shell courses, roof supports, corrosion, sludge, and coating when the tank is safely cleaned and isolated. Level alarms and independent overfill protection are tested on schedule. Any settlement, shell deformation, foundation cracking, roof damage, or leak is reported immediately. Inspection reports identify defects, fitness-for-service decision, repair scope, and next due date. Tank return to service requires cleanliness, valve line-up, instrument test, and Operations acceptance."),
    _r("maintenance", "Spare parts criticality and storage", "Neha Singh, Maintenance Manager", "All zones", "Warehouse and rotating equipment spares", "spares criticality preservation pump seal bearing", "Spare parts are ranked by safety consequence, production impact, lead time, and interchangeability. Critical spares include pump cartridges, mechanical seals, bearings, instrument transmitters, motor starters, and emergency valves where the risk assessment requires them. Preservation checks cover humidity, shaft rotation, desiccant, packaging, shelf life, and corrosion protection. The warehouse records part number, equipment compatibility, quantity, location, condition, and next preservation date. A part removed from stores is not considered available until its compatibility and condition are verified. Substitutions require Engineering approval and a documented technical review."),
    _r("maintenance", "Bad-actor equipment review", "Mohan Iyer, Reliability Engineer", "All zones", "Reliability dashboard", "bad actor analysis repeat failure MTBF RCA", "The reliability team reviews repeat failures, unplanned trips, high maintenance cost, safety-critical degradation, and low mean time between failures. A bad actor is selected using evidence from work orders, condition monitoring, operator logs, and production impact. The review identifies failure mode, cause, detection gap, temporary action, permanent action, owner, due date, and effectiveness measure. Replacing the failed part without addressing the failure mechanism is not a complete action. The monthly review ranks open actions and reports overdue items to the Maintenance Manager and Area Manager. Completed actions require evidence of improved performance."),

    # Process control, quality, and laboratory.
    _r("process", "Crude quality and assay handling", "Anita Rao, Laboratory Manager", "Zone A", "Crude receipt laboratory", "crude assay density sulfur water sediment sample", "Each crude receipt is associated with supplier, parcel, tank, date, temperature, density, sulfur, water and sediment, salt, and assay information when available. Samples are taken using the approved representative sampling method and labeled at the point of collection. The laboratory checks sample integrity and chain of custody before analysis. Process Engineering uses assay results to confirm blend suitability and furnace or desalter operating expectations. A missing, contaminated, or disputed sample places the relevant movement under a quality hold until the Laboratory Manager and Operations Superintendent agree on disposition. Results are stored against the movement and tank, not only in a paper notebook."),
    _r("process", "Desalter operating guideline", "Kavita Iyer, Process Engineer", "Zone B", "Crude desalter", "desalter temperature wash water voltage interface", "Stable desalter operation depends on crude temperature, wash-water ratio, mixing, electrostatic field, interface level, and salt removal. Operators monitor inlet temperature, pressure drop, water rate, electrical load, interface indication, brine discharge, and downstream salt results. Increasing water without checking mixing or interface can worsen carryover. A high interface, emulsion, electrical trip, or high salt result requires controlled response using the desalter troubleshooting sheet. Do not open the vessel or bypass protection while energized. The panel operator records changes and result timing so Process Engineering can distinguish process response from analyzer delay."),
    _r("process", "Furnace operation and draft control", "Kavita Iyer, Process Engineer", "Zone B", "Crude furnace F-201", "furnace operation draft bridgewall temperature burner", "Furnace operators maintain the approved firing rate, bridgewall temperature, stack oxygen, draft, fuel pressure, and tube-skin temperature envelope. Burner flame must be stable and visually acceptable where observation is safe. Uneven flame, high tube-skin temperature, flame impingement, smoke, loss of draft, or fuel-gas pressure fluctuation requires rate reduction or shutdown action according to the operating procedure. Soot blowing and burner adjustment are coordinated with the panel operator. Furnace trips are never reset repeatedly without cause investigation. Trend records include feed rate, outlet temperature, fuel rate, oxygen, draft, and the time of each operator intervention."),
    _r("process", "Pipeline pressure operating envelope", "Imran Sheikh, Pipeline Controller", "Zone C", "L09 and L10 pipelines", "pipeline pressure limit L09 3.5 5.5 bar", "The normal L09 pressure envelope is 3.5 to 5.5 bar during approved transfer. The alert threshold is 5.5 bar and the high action threshold is 6.0 bar. Pressure below 3.0 bar may indicate loss of pump performance, leak, wrong valve position, vapor formation, or empty source conditions. The controller compares pressure at the pump discharge, intermediate station, and receiving end. A mismatch requires rate hold and field verification. Pressure data is recorded with flow, temperature, tank level, and valve line-up. Any suspected leak takes priority over maintaining throughput; isolate only according to the emergency isolation plan."),
    _r("process", "Mass balance and tank reconciliation", "Kavita Iyer, Process Engineer", "All zones", "Movement and inventory records", "mass balance tank reconciliation crude product", "Daily reconciliation compares opening inventory, receipts, production, transfers, dispatches, samples, water draw, and closing inventory. Levels are corrected for temperature and tank calibration where applicable. The process engineer flags unexplained variance rather than changing a measurement to make the balance close. Investigations check meter proving, level-gauge health, valve passing, unrecorded movements, density assumptions, and timing differences. A variance above the site threshold is reviewed by Operations, Laboratory, and Finance as relevant. The final record states data sources, calculation date, variance, probable cause, action, owner, and whether the movement is on quality or custody-transfer hold."),
    _r("process", "Flow meter proving and custody transfer", "Joseph Thomas, Instrumentation Lead", "Zones A and C", "Crude and product meters", "flow meter proving custody transfer K factor", "Custody-transfer meters are operated within their approved flow, pressure, temperature, and viscosity range. Proving compares indicated volume with a traceable prover or approved master meter and calculates meter factor. The record includes meter tag, product, temperature, pressure, flow rate, prover identity, pulses, observed volume, meter factor, repeatability, and acceptance decision. A failed prove blocks use for custody transfer until the discrepancy is evaluated. Process operators do not alter K factors without authorization and a controlled change record. The meter run remains accessible, sealed where required, and protected from unauthorized bypass."),
    _r("process", "Blending quality release guideline", "Anita Rao, Laboratory Manager", "Zone D", "Finished product blending", "product quality release density flash point sulfur RON", "A batch is released only after required laboratory tests meet the current product specification and the batch record is complete. Typical checks may include density, sulfur, flash point, distillation, octane or cetane, water, color, conductivity, and additive marker depending on product. The laboratory verifies sample identity and retains a reference sample under the retention procedure. An out-of-specification result creates a quality hold, prevents dispatch, and starts a documented investigation. Reblend or downgrade requires Quality and Operations approval. Verbal release is not sufficient; dispatch sees the electronic release status and batch number."),
    _r("process", "Water draw and sediment control", "Asha Menon, Area Manager", "Zone A", "Crude storage tanks", "tank water draw sediment interface drain", "Water draw removes free water and sediment from storage tanks using the approved drain route and controlled opening sequence. Before opening, verify drain destination, containment, valve identity, and operator communication. Open slowly and observe the first liquid. Stop if hydrocarbon appears, the drain surges, the bund level rises, or the route is blocked. Record start time, stop time, water volume or interface observation, tank level, and any hydrocarbon recovery. Water with hydrocarbon contamination is handled as controlled waste. Repeated water accumulation triggers a tank, crude, roof-drain, or water-ingress investigation rather than indefinite manual draining."),
    _r("process", "Steam system operating guideline", "Priya Das, Utilities Supervisor", "Zone E", "Steam headers and traps", "steam header pressure condensate trap water hammer", "Steam operators maintain header pressure, boiler load, condensate return, trap condition, and user demand within the utility operating plan. Warm-up is gradual to prevent water hammer. Drains are opened through the approved sequence and closed after condensate is cleared. A hammer event, unusual trap noise, high condensate level, or pressure swing is reported immediately. Steam traps are surveyed by route and defective traps receive a work order. Users must not vent steam continuously as a substitute for fixing a failed control valve or trap. The control room records major header changes and communicates planned load changes to affected zones."),
    _r("process", "Instrument air quality and pressure", "Joseph Thomas, Instrumentation Lead", "Zone E", "Instrument air compressors and dryers", "instrument air 5.5 barg dew point compressor dryer", "Instrument air is maintained clean, dry, and at a normal header pressure of at least 5.5 barg. The low operating alert is 5.0 barg. Operators check compressor loading, dryer status, receiver drains, filter differential pressure, moisture indicators, and standby availability. Automatic drains are tested and manual drains are performed safely. A low-pressure event requires the control room to identify affected valves, move critical equipment to its safe state, and isolate nonessential users if directed. No oily shop air may be connected to instrument air. Dew point excursions are investigated for dryer failure, drain blockage, or header contamination."),

    # Environmental, logistics, and governance.
    _r("environment", "Waste segregation and manifest guideline", "Meera Joshi, HSE Manager", "All zones", "Hazardous and non-hazardous waste yards", "waste segregation hazardous manifest used oil sludge", "Waste is identified at the point of generation, placed in compatible labeled containers, and kept closed except during filling. Used oil, oily rags, contaminated soil, spent catalyst, laboratory chemicals, batteries, scrap metal, and general waste use separate streams. The generator records source zone, waste description, quantity, date, hazards, and responsible person. Hazardous waste leaves the site only with an approved manifest and authorized transporter. Leaking or incompatible containers are isolated and corrected immediately. Burning, burying, mixing, or unrecorded disposal is prohibited. Monthly inspections check labels, secondary containment, capacity, housekeeping, and emergency equipment."),
    _r("environment", "Effluent monitoring and response", "Meera Joshi, HSE Manager", "Zone A", "Effluent treatment system", "effluent pH oil COD discharge monitoring", "The effluent system receives segregated streams through approved routes and monitors flow, pH, oil and grease, temperature, suspended solids, and other parameters in the site consent. Operators check equalization tank level, skimmer condition, chemical dosing, aeration, sludge handling, and final discharge status. A pH excursion, visible oil sheen, abnormal odor, high conductivity, or analyzer failure requires containment and notification to HSE and the control room. No bypass is opened to avoid an exceedance. Samples follow the chain-of-custody procedure. The event record includes time, source, flow, result, immediate action, recovery, and regulator-reporting assessment."),
    _r("environment", "Flare and emissions observation guideline", "Kavita Iyer, Process Engineer", "Zones B and C", "Flare header and stack", "flare smoke radiation emissions observation", "The flare system provides controlled disposal for relief and emergency gases. Operators monitor header pressure, knockout drum level, pilot status, flame, smoke, purge, seal condition, and radiation boundary. Black smoke, repeated flameout, liquid carryover, unusual noise, or high knockout level is escalated immediately. Planned flaring requires approval, estimated duration, material, reason, and emissions estimate where applicable. Personnel remain outside the radiation boundary and do not approach the flare structure for visual checks. Flare observations are logged with weather, process event, duration, and corrective action. Flare alarms and trips are not bypassed without formal authorization."),
    _r("environment", "Energy conservation operating practices", "Eshan Verma, Utilities Manager", "All zones", "Plant energy systems", "energy conservation steam fuel electricity efficiency", "Operators support energy efficiency by maintaining furnace excess oxygen, preventing steam leaks, returning condensate, keeping heat-exchanger surfaces clean, using the correct pump configuration, and shutting down idle equipment when safe. The control room reviews fuel gas, steam, electricity, cooling water, and compressed-air consumption against production-normalized targets. A sudden increase is investigated for leaks, fouling, control instability, meter error, or changed feed. Energy actions must not defeat safety or quality controls. Each monthly improvement record states baseline, action, measured result, calculation method, owner, and verification period."),
    _r("environment", "Stormwater and monsoon preparedness", "Meera Joshi, HSE Manager", "All zones", "Drains, bunds, and stormwater network", "monsoon stormwater drain bund rain preparedness", "Before heavy rain, inspect stormwater drains, culverts, bund walls, tank farm sumps, oily-water separators, pumps, and temporary covers. Keep clean stormwater and contaminated drainage segregated. Confirm emergency pumps, generators, hoses, lighting, and access routes. During rain, monitor bund levels and prevent product-contaminated water from leaving the controlled system. Stop transfer if flooding threatens valves, motors, electrical equipment, or containment. After the event, inspect foundations, pipe supports, roads, erosion, electrical rooms, and tank farm integrity. Record rainfall, water levels, pump operation, samples, releases, and corrective actions in the environmental log."),
    _r("logistics", "Crude receipt scheduling and berth interface", "Asha Menon, Supply Coordinator", "Zone A", "Receipt schedule and marine interface", "crude receipt schedule berth nomination demurrage", "Crude receipt scheduling reconciles nominated parcel, expected arrival, quality documents, berth readiness, tank capacity, line availability, and laboratory coverage. The Supply Coordinator shares the movement plan with Operations, Marine, Laboratory, HSE, and Finance. Before transfer, Operations confirms tank space, route line-up, meter readiness, emergency shutdown communications, and sampling plan. Delays, quality uncertainty, weather, or berth changes are recorded with time and decision owner. No receipt begins solely on a verbal nomination. The final movement pack includes quantity, quality, tank, meter readings, sample references, times, and any variance or claim."),
    _r("logistics", "Product dispatch documentation", "Farah Khan, Dispatch Manager", "Zone D", "Road and pipeline dispatch", "product dispatch invoice batch release gate pass", "Dispatch documents must match product, batch, quantity, destination, vehicle or pipeline route, quality release, seal numbers, and loading time. The loading supervisor checks the electronic release status before opening the loading arm. Corrections are made through the controlled amendment process; handwritten changes without authorization are not valid. The gate verifies vehicle identity, driver authorization, safety equipment, seal, and quantity document. Any mismatch stops dispatch until resolved by Dispatch and Quality. Daily reconciliation compares planned, loaded, and dispatched quantities and records cancellations, short loads, returns, and damaged seals."),
    _r("logistics", "Warehouse receiving and material traceability", "Leena Kapoor, Materials Manager", "All zones", "Central warehouse", "warehouse receipt inspection material traceability", "Warehouse receiving verifies purchase order, supplier, part number, quantity, condition, certification, shelf life, and preservation requirements. Safety-critical or pressure-containing items require material certificates and inspection acceptance before release. Damaged, wrong, expired, or uncertified material is quarantined and clearly labeled. Items are stored by compatibility and environmental requirement. The inventory record links item to equipment tag where practical, especially for relief devices, seals, bearings, instruments, and electrical protection components. Issue transactions record receiver, work order, quantity, and return status. Substitution or local fabrication requires Engineering approval and inspection evidence."),
    _r("logistics", "Fuel and chemical unloading guideline", "Eshan Verma, Utilities Manager", "Zone E", "Chemical unloading station", "chemical unloading tanker hose compatibility SDS", "Before unloading a chemical or fuel, verify supplier, product, concentration, tank identity, available capacity, connection compatibility, hose condition, grounding, spill containment, emergency shower, and current SDS. The unloading supervisor conducts a pre-job briefing with the driver and field operator. Valves are identified and independently checked. Start slowly and monitor level, pressure, leaks, and hose movement. Stop for unexpected pressure, odor, leak, high level, loss of grounding, or communication failure. Disconnect only after line pressure is relieved and valves are closed. Record quantity, tank, batch or lot, start and finish time, sample, and any deviation."),
    _r("governance", "Management of change procedure", "Nitin Bose, MOC Coordinator", "All zones", "Temporary and permanent changes", "MOC management of change process risk review training drawings", "Management of Change applies to process conditions, equipment, chemicals, software, alarms, procedures, organization, and temporary modifications that can affect risk or performance. The initiator describes current state, proposed change, reason, duration, hazards, affected documents, and reversibility. Process, mechanical, electrical, instrumentation, Operations, HSE, and training impacts are reviewed according to the change. Actions include drawings, setpoints, spares, procedures, competency, emergency response, and inspection. The change is not commissioned until approvals and pre-startup checks are complete. Temporary changes have an expiry date and owner; overdue temporary changes are escalated."),
    _r("governance", "Permit to work governance", "Leena Kapoor, HSE Lead", "All zones", "Permit office and job sites", "permit to work cold work hot work excavation isolation", "The permit issuer verifies scope, location, hazards, isolations, gas tests, PPE, simultaneous operations, rescue, and validity period. The performing authority explains controls to the work party and keeps the permit at the job site. The permit does not authorize work outside the stated boundary or after conditions change. Suspension is required for alarms, weather, shift change without handover, loss of isolation, or changed process conditions. Revalidation confirms the work remains safe; it is not an automatic extension. At completion, the area is inspected, tools and personnel are accounted for, guards restored, and the permit formally closed."),
    _r("governance", "Process safety indicator review", "Meera Joshi, HSE Manager", "All zones", "Process safety dashboard", "process safety KPI PSE trip loss containment alarm bypass", "The monthly process safety review tracks loss of primary containment, high-potential near misses, demand on safety systems, overdue proof tests, alarm standing time, bypass duration, emergency shutdown activations, relief-device lifts, permit deviations, and critical equipment availability. Indicators are interpreted with production context; a low event count does not prove low risk. Each negative trend has an owner, action, due date, and effectiveness measure. The review separates immediate correction from systemic learning. Site leadership checks that actions are closed with evidence and that recurring events receive a formal causal analysis rather than repeated reminders."),
    _r("governance", "Training and competency matrix", "Leena Kapoor, Training Lead", "All zones", "Role competency records", "training competency operator authorization refresher", "The competency matrix lists role, task, required knowledge, practical demonstration, assessor, initial qualification, refresher interval, and expiry. Critical tasks include control-room operation, tank receipt, pipeline line-up, isolation, confined space, gas testing, firefighting, sampling, and emergency response. A person may observe before qualification but may not perform an authorized task independently. Supervisors verify current competency during roster planning and stop assignment when certification expires. Lessons from incidents, MOC, procedure revisions, and equipment changes trigger targeted retraining. Training records contain evidence of attendance and assessment, not just a completion tick."),
    _r("governance", "Incident and near-miss investigation", "Meera Joshi, HSE Manager", "All zones", "Event reporting system", "incident near miss investigation root cause corrective action", "All incidents, near misses, unsafe conditions, and process safety events are reported promptly, even when there is no injury or production loss. The initial report records who, what, where, when, immediate controls, material, equipment, witnesses, and photos where safe. The investigation team uses evidence and avoids blame. Causes are tested against failed barriers, management systems, human factors, design, maintenance, and operating conditions. Actions are specific, owned, dated, and verifiable. The event is not closed until actions are implemented and effectiveness is reviewed. Learning is shared with affected zones and incorporated into procedures or training when needed."),
    _r("governance", "Audit and inspection finding closure", "Nitin Bose, Assurance Manager", "All zones", "Assurance action register", "audit finding corrective action due date evidence", "Audit findings are classified by risk and assigned to an accountable owner. The response states containment, root cause, corrective action, preventive action, due date, and evidence required. Rewording a procedure without checking field practice does not close a finding. The Assurance Manager verifies objective evidence, interviews affected personnel, and samples implementation. Overdue high-risk findings are escalated to the Area Manager and Operations Superintendent. Repeated findings are grouped for systemic action. The register retains original wording, current status, extension approval, closure evidence, verifier, and closure date so the history remains auditable."),
    _r("governance", "Cyber and control-system access guideline", "Joseph Thomas, Control Systems Lead", "All zones", "DCS, PLC, and historian access", "DCS access account cyber security historian remote access", "Control-system access uses named accounts, least privilege, approved changes, and time-bound remote access where permitted. Shared passwords are prohibited. USB media, laptops, and engineering workstations are controlled and scanned under the site cyber procedure. Operators report unexpected screens, alarm floods, loss of historian data, unauthorized setpoint changes, or unusual login prompts to the Control Systems Lead and control room. Changes to PLC, DCS, SIS, historian, or network equipment require backup, testing, rollback plan, authorization, and a maintenance window. Cyber response preserves evidence; staff do not reboot or delete files unless directed."),
    _r("governance", "Operations data quality and dashboard use", "Sanjay Kulkarni, Operations Superintendent", "All zones", "Shift logs, historian, and boards", "operations data quality dashboard reading timestamp", "Operational readings entered into a dashboard must include metric identity, value, unit, recorded time, and person or system that entered the value. Staff correct a mistake by adding a corrected reading with an explanation; they do not silently overwrite history. A stale reading is marked stale according to the dashboard policy and must not be presented as current. The control room compares dashboard values with approved instruments or records when a decision depends on them. Dashboards support situational awareness but do not replace SIS, DCS alarms, permits, logbooks, or approved operating procedures."),
]

# Additional plant references bring the catalog to 100 documents and give
# demonstrations more realistic retrieval targets across many departments.
RECORDS += [
    _r("sop", "Pump seal leak response", "Neha Singh, Maintenance Manager", "Zone C", "P-204 mechanical seal", "pump seal leak response shutdown", "If seal leakage is visible, notify the control room, reduce rate when safe, check the standby route, and prepare a controlled changeover. Do not touch a pressurized seal or spray water onto hydrocarbon leakage. A persistent or increasing leak requires isolation and maintenance under permit."),
    _r("sop", "Pipeline pigging preparation", "Imran Sheikh, Pipeline Controller", "Zone C", "L09 pig launcher", "pipeline pigging launcher receiver isolation", "Pigging requires an approved plan, product compatibility check, launcher and receiver isolation, pressure verification, communication with every valve station, and a recovery plan. The controller records pig identity, launch pressure, receive time, line pressure, and any debris or abnormality."),
    _r("sop", "Tank level gauge verification", "Joseph Thomas, Instrumentation Lead", "Zone A", "TK-103 level gauge", "tank level gauge verification independent level", "Compare the primary level indication with the independent gauge and physical inventory where practical. Investigate disagreement before a receipt or dispatch decision. Record tank temperature, level, gauge identity, time, and verification result; never adjust a transmitter to match an expected number."),
    _r("sop", "Desalter brine draw operation", "Kavita Iyer, Process Engineer", "Zone B", "Desalter brine system", "desalter brine draw interface operation", "Open the brine draw through the approved route and observe interface response, salt water appearance, and downstream water carryover. Stop for hydrocarbon in the drain, unstable interface, or unexpected pressure. Record duration, interface, rate, and action in the unit log."),
    _r("sop", "Compressor startup checklist", "Vikram Rao, Utilities Engineer", "Zone E", "Instrument air compressor C-02", "compressor startup suction discharge oil pressure", "Confirm oil level, cooling, suction filter, discharge route, unloader, vibration switch, and permissives before startup. Start unloaded, establish oil pressure, verify discharge pressure and current, then load gradually. Stop for high vibration, low oil pressure, or abnormal noise."),
    _r("sop", "Emergency generator test", "Joseph Thomas, Electrical Lead", "Zone E", "Emergency generator DG-01", "emergency generator test fuel battery load transfer", "The monthly test verifies fuel, battery, coolant, exhaust, automatic start, transfer permissive, load acceptance, and return to normal supply. Notify affected users before the test. Record start time, voltage, frequency, load, alarms, fuel level, and any failed permissive."),
    _r("sop", "Laboratory sample chain of custody", "Anita Rao, Laboratory Manager", "All zones", "Sample room and laboratory", "sample chain custody label laboratory result", "Each sample receives a unique number, source, equipment or tank, date, time, sampler, preservation, requested tests, and receiving analyst. Broken seals, missing labels, delayed delivery, or temperature excursions are recorded and assessed before results are released."),
    _r("sop", "Chemical injection pump changeover", "Eshan Verma, Utilities Manager", "Zone E", "Corrosion inhibitor pump CI-01", "chemical injection pump changeover dosage standby", "Verify chemical tank level, suction and discharge valves, calibration pot, leak-free tubing, and standby pump readiness. Start standby at the approved stroke or speed, confirm injection response, then stop duty pump. Record rate and reason for changeover."),
    _r("sop", "Firewater pump weekly test", "Meera Joshi, HSE Manager", "All zones", "Firewater pump house", "firewater pump test jockey diesel pressure", "Weekly testing confirms pump start, header pressure, diesel condition, jockey pump, valves, alarms, and return-to-ready status. Avoid draining contaminated water to stormwater. Record suction and discharge pressure, running time, battery voltage, fuel, and defects."),
    _r("sop", "Truck bay emergency stop test", "Farah Khan, Loading Supervisor", "Zone D", "Loading bay E-stop", "loading bay emergency stop test reset", "Test emergency stops under the approved maintenance window and notify all loading bays. Confirm pumps stop, valves move to the safe state, alarms appear in the control room, and reset requires authorization. Record test result and any unavailable bay."),
    _r("safety", "Job safety analysis guideline", "Leena Kapoor, HSE Lead", "All zones", "Pre-job planning", "JSA hazard controls hierarchy of controls", "A job safety analysis identifies steps, hazards, consequences, existing safeguards, additional controls, responsible person, and stop conditions. The crew reviews it at the worksite and updates it when scope or conditions change. Generic copied JSAs do not replace task-specific review."),
    _r("safety", "Line breaking safety guideline", "Leena Kapoor, HSE Lead", "All zones", "Flanges, drains, and sample points", "line breaking hydrocarbon pressure drain PPE", "Line breaking requires positive isolation where specified, depressurization, draining, gas testing, splash protection, compatible PPE, and a controlled opening direction. Crack the joint only after the permit issuer confirms zero energy. Stop for pressure, odor, liquid, unexpected temperature, or wrong equipment identity."),
    _r("safety", "Excavation and underground service control", "Leena Kapoor, HSE Lead", "All zones", "Roads and underground services", "excavation permit cable pipeline utility scan", "Excavation needs a permit, drawing review, service scan, trial holes, barricades, access, spoil control, and inspection after rain or change. Hand digging is required near identified services. A damaged cable or pipeline triggers stop-work, isolation, emergency response, and notification."),
    _r("safety", "Radiation source control guideline", "Meera Joshi, HSE Manager", "Zones B and C", "Level and density gauges", "radiation source gauge exclusion area", "Radiation sources are tagged, secured, surveyed, and handled only by authorized personnel. Work near a source requires notification, boundary control, dosimetry where required, and a source-status check. Suspected damage or loss is reported immediately; staff must not handle a source or enter a controlled boundary."),
    _r("safety", "PPE selection matrix", "Leena Kapoor, HSE Lead", "All zones", "Task PPE", "PPE matrix helmet goggles gloves respirator", "PPE is selected from the task hazard assessment and chemical compatibility information. Minimum site PPE does not cover every task. Inspect gloves, face shields, respirators, footwear, and fall protection before use. Damaged or contaminated PPE is removed from service and replaced."),
    _r("safety", "Heat stress prevention guideline", "Meera Joshi, HSE Manager", "All zones", "Outdoor and hot process areas", "heat stress hydration work rest monitoring", "Supervisors plan heavy work for cooler periods, provide water and shaded recovery, use acclimatization, and monitor symptoms. Confusion, faintness, cramps, or loss of coordination requires immediate cooling, first aid, and medical assessment. Heat controls are increased during furnace, tank farm, and summer outdoor work."),
    _r("safety", "Driving and site traffic rules", "Farah Khan, Security Lead", "All zones", "Internal roads and gates", "site driving speed limit seatbelt tanker", "Drivers obey posted speed limits, seat belts, one-way routes, reversing controls, parking restrictions, and tanker loading rules. Mobile-phone use while driving is prohibited. Pedestrians use marked routes. An incident, near miss, vehicle defect, or spill from a vehicle is reported to Security and HSE."),
    _r("safety", "Drill planning and learning", "Meera Joshi, Emergency Director", "All zones", "Emergency drills", "emergency drill exercise critique action", "Drills have an objective, scenario, participants, boundaries, observers, stop phrase, and evaluation criteria. The controller records alarm time, response, communication, muster, equipment, and recovery. A hot debrief captures strengths and gaps; actions receive owners and due dates."),
    _r("maintenance", "Motor condition monitoring", "Joseph Thomas, Electrical Lead", "All zones", "Motors and MCC feeders", "motor current insulation resistance bearing temperature", "Motor health uses current balance, insulation results, bearing temperature, vibration, starts, trips, and visual condition. Repeated overloads or unbalanced current require load and alignment review. Electrical testing is performed isolated by authorized staff and results are compared with historical trends."),
    _r("maintenance", "Pump alignment acceptance", "Neha Singh, Maintenance Manager", "All zones", "Pump and driver trains", "pump alignment laser soft foot coupling", "Before coupling, technicians check soft foot, base condition, shaft and coupling runout, pipe strain, and alignment. Acceptance records show method, tolerances, as-found and as-left values, shims, and technician. A successful no-load run does not replace a loaded performance check."),
    _r("maintenance", "Relief valve discharge inspection", "Mohan Iyer, Reliability Engineer", "All zones", "Relief discharge piping", "relief valve discharge inspection corrosion drain", "Inspect discharge piping supports, corrosion, drain condition, vent termination, caps, and access. Blockage, liquid accumulation, damaged support, or unauthorized isolation is escalated as an integrity concern. Inspection records link the discharge path to the PSV tag and latest test certificate."),
    _r("maintenance", "Pipe support and rack inspection", "Mohan Iyer, Reliability Engineer", "Zones B and C", "Pipe racks and supports", "pipe support inspection rack corrosion shoe guide", "Rounds check shoes, guides, anchors, spring supports, clamps, corrosion, distortion, hot alignment, and contact with neighboring lines. Missing or seized supports can transfer loads into equipment nozzles. Photograph and tag defects, assess immediate risk, and track repair through the integrity register."),
    _r("maintenance", "Valve packing leak management", "Neha Singh, Maintenance Manager", "All zones", "Process valve packing", "valve packing leak fugitive emission tightening", "Small packing leaks are recorded and assessed for service, pressure, toxicity, and escalation rate. Tightening is done only by approved method and does not substitute for isolation where risk is high. A leak that worsens, sprays, or affects personnel access requires immediate control-room notification."),
    _r("maintenance", "Calibration analyzer quality checks", "Anita Rao, Laboratory Manager", "Zones B and D", "Online quality analyzers", "online analyzer validation sample calibration", "Online analyzers are checked against certified or laboratory samples at the scheduled interval. Drift, sample-system blockage, bad conditioning, and analyzer alarms are investigated. Product release decisions use an approved fallback method while the analyzer is unavailable; the fallback and duration are recorded."),
    _r("maintenance", "Spill kit inspection", "Meera Joshi, HSE Manager", "All zones", "Spill response lockers", "spill kit inspection absorbent boom drain cover", "Monthly inspection confirms absorbent, drain covers, gloves, goggles, bags, shovel, labels, and inventory sign. Used material is replenished and disposed of as controlled waste. Spill kits remain accessible and are not borrowed for routine housekeeping without replacement."),
    _r("maintenance", "Fire extinguisher inspection", "Meera Joshi, HSE Manager", "All zones", "Portable extinguishers", "fire extinguisher inspection pressure seal access", "Inspectors verify type, pressure, pin, seal, hose, nozzle, body, mounting, signage, and access. A discharged, damaged, expired, or inaccessible extinguisher is removed and replaced immediately. Inspection records identify location and asset number."),
    _r("maintenance", "Cooling water chemistry monitoring", "Eshan Verma, Utilities Manager", "Zone E", "Cooling tower basin", "cooling water pH conductivity biocide blowdown", "Utilities monitor pH, conductivity, inhibitor, biocide, temperature, and blowdown. Chemical dosing follows the treatment plan and verified pump rate. High conductivity, biological growth, corrosion products, or abnormal makeup demand triggers treatment review and affected-user notification."),
    _r("maintenance", "Electrical thermography program", "Joseph Thomas, Electrical Lead", "All zones", "MCCs and switchboards", "thermography hot connection electrical inspection", "Thermography is performed under safe operating conditions by competent personnel. Results are compared with phase balance, load, ambient condition, and previous images. A hot connection is risk-ranked and corrected under isolation; the image, temperature, load, and action are retained."),
    _r("process", "Crude blend compatibility review", "Kavita Iyer, Process Engineer", "Zone A", "Crude blend planning", "crude blend compatibility stability sediment", "Before blending parcels, Process Engineering reviews assay, density, sulfur, acidity, asphaltene tendency, water, sediment, and known incompatibilities. A small-scale compatibility test or additional controls may be required. The blend decision records data, expected operating impact, tank, and approval."),
    _r("process", "Tank farm vapor control", "Asha Menon, Area Manager", "Zone A", "Tank vents and vapor recovery", "tank vapor control vent pressure vapor recovery", "Vapor control equipment remains available during receipt and transfer. Operators monitor pressure, vent condition, recovery-unit status, flame arresters, and alarm health. High tank pressure, vacuum, odor, or recovery failure requires rate control and supervisor notification; vents are not manually defeated."),
    _r("process", "Column overhead system monitoring", "Kavita Iyer, Process Engineer", "Zone B", "CDU overhead condenser", "column overhead pressure condenser reflux accumulator", "The panel operator trends overhead pressure, condenser outlet temperature, reflux, accumulator level, sour-water draw, and corrosion indicators. A pressure rise may reflect fouling, cooling loss, non-condensable load, or downstream restriction. Troubleshooting follows the unit sheet and protects against overpressure."),
    _r("process", "Fuel gas pressure management", "Priya Das, Utilities Supervisor", "Zones B and E", "Fuel gas header", "fuel gas pressure furnace burner low pressure", "Fuel gas users stay within approved pressure and composition limits. Operators monitor header pressure, knockout drums, filters, flame stability, and low-pressure alarms. A pressure drop requires load reduction and coordination; repeated burner trips are investigated rather than repeatedly reset."),
    _r("process", "Product tank changeover", "Farah Khan, Loading Supervisor", "Zone D", "Finished product tanks", "product tank changeover line up segregation", "Tank changeover uses an approved sequence, independent valve verification, quality status, available capacity, and communication with dispatch. Confirm previous product clearance and additive route before opening the new tank. Record levels before and after and investigate unexpected movement."),
    _r("process", "Pipeline leak detection review", "Imran Sheikh, Pipeline Controller", "Zone C", "L09 leak detection", "pipeline leak detection balance pressure flow", "The controller compares inlet and outlet flow, pressure profile, tank level, valve state, and route observations. A sustained unexplained imbalance or pressure decay is treated as a possible leak until disproven. Rate is reduced or transfer stopped according to the emergency plan and the area is inspected safely."),
    _r("process", "Meter data reconciliation", "Joseph Thomas, Instrumentation Lead", "Zones A and C", "Custody transfer meters", "meter reconciliation pulses totalizer flow data", "Daily meter reconciliation compares totalizer, historian, proving factor, manual readings, temperature compensation, and movement documents. Gaps or resets are documented. Unexplained differences are escalated to Instrumentation and Finance or Supply before a custody claim is accepted."),
    _r("process", "Laboratory result review", "Anita Rao, Laboratory Manager", "All zones", "Laboratory information system", "lab result review QA QC sample approval", "Analysts review blanks, standards, duplicates, control charts, instrument status, and sample identity before releasing a result. Outliers are checked against sample history and process conditions. A result is not released when quality controls fail unless the Laboratory Manager documents the disposition."),
    _r("process", "Wastewater oil separator operation", "Meera Joshi, HSE Manager", "Zone A", "API separator", "oil water separator skimmer sludge operation", "Operators check inlet flow, separator level, skimmer, sludge, outlet clarity, and alarms. Skimmed oil and sludge are labeled and transferred to approved waste storage. A bypass, sheen, blocked coalescer, or high outlet oil result requires containment and HSE notification."),
    _r("process", "Nitrogen header pressure monitoring", "Joseph Thomas, Instrumentation Lead", "Zone A", "Nitrogen header", "nitrogen header pressure inerting supply", "The header is monitored for pressure, source availability, non-return protection, and demand. A low header pressure can affect inerting and safe storage conditions; notify the control room and Utilities. Unauthorized connections and uncontrolled venting are prohibited."),
    _r("logistics", "Inventory cycle count guideline", "Leena Kapoor, Materials Manager", "All zones", "Warehouse inventory", "inventory cycle count stock variance critical spare", "Cycle counts prioritize safety-critical, high-value, high-use, and shelf-life-controlled items. Counters verify part number, quantity, bin, condition, and preservation. Variance is investigated against receipts, issues, returns, and substitutions; the system is not adjusted without an approved reason."),
    _r("logistics", "Tank truck inspection standard", "Farah Khan, Loading Supervisor", "Zone D", "Road tankers", "tanker inspection certificate tires emergency equipment", "Before entry and loading, Security and Loading verify vehicle certificate, tires, brakes, grounding point, fire extinguisher, spill kit, emergency stop interface, compartments, seals, and driver induction. Unsafe vehicles are rejected and recorded; production urgency does not waive checks."),
    _r("logistics", "Pipeline transfer nomination", "Sanjay Kulkarni, Supply Coordinator", "Zone C", "Pipeline movement schedule", "pipeline nomination transfer order source destination", "The movement order states source, destination, product, quantity, rate, start window, line, tank capacity, quality status, contacts, and stop conditions. Changes are acknowledged by both ends and entered in the movement log. A verbal change without a controlled order is not sufficient."),
    _r("logistics", "Material preservation inspection", "Neha Singh, Maintenance Manager", "All zones", "Stored rotating equipment", "spare preservation humidity bearing shaft rotation", "Preservation routes inspect packaging, humidity, desiccant, corrosion inhibitor, shaft rotation, seals, and storage environment. Failed preservation creates a condition hold and maintenance assessment. The inventory record shows last inspection, next due date, and corrective action."),
    _r("logistics", "Visitor and contractor access control", "Farah Khan, Security Lead", "All zones", "Main gate and passes", "visitor access contractor badge escort security", "Visitors provide identity, sponsor, purpose, access boundary, emergency briefing, and escort requirement. Badges are returned at exit and visitor counts reconcile during an emergency. Contractors cannot enter a process area with an expired induction, missing PPE, or unverified work authorization."),
    _r("governance", "Operating envelope register", "Kavita Iyer, Process Engineer", "All zones", "Approved limits register", "operating envelope pressure temperature flow alarm limit", "The operating envelope register lists normal, alert, action, and design values with units, source, revision, and owner. Operators use the current register and report drift. A proposed limit change requires engineering review, MOC, alarm review, training, and controlled publication."),
    _r("governance", "Critical alarm bypass register", "Sanjay Kulkarni, Operations Superintendent", "All zones", "Alarm and trip bypasses", "alarm bypass register expiry compensating measure", "Every bypass records equipment, protection, reason, start time, approver, compensating measure, owner, expiry, and restoration test. The control room reviews the register each shift. Expired bypasses are escalated; bypassing a protection without authorization is prohibited."),
    _r("governance", "Turnaround planning standard", "Neha Singh, Maintenance Manager", "All zones", "Planned shutdown and turnaround", "turnaround planning scope isolation critical path", "Turnaround scope is risk-ranked and integrated across Operations, Maintenance, Inspection, HSE, Materials, and contractors. The plan includes isolation, cleaning, access, critical path, spares, inspection hold points, testing, startup, and contingency. Scope growth is controlled through an approved change process."),
    _r("governance", "Startup readiness review", "Sanjay Kulkarni, Operations Superintendent", "All zones", "Post-maintenance startup", "startup readiness PSSR equipment release line up", "Before startup, the team confirms construction complete, guards installed, punch-list status, instruments tested, alarms and trips available, procedures current, operators trained, permits closed, chemicals available, and line-up independently verified. The readiness record names approvers and unresolved risks."),
    _r("governance", "Shift performance review", "Sanjay Kulkarni, Operations Superintendent", "All zones", "Daily operations meeting", "daily production review safety quality energy", "The daily review covers safety events, production, quality, energy, utilities, tank and pipeline status, maintenance constraints, environmental readings, dashboard data quality, and actions. Numbers are traceable to the source record and deviations have an owner and due date."),
    _r("governance", "Engineering calculation review", "Kavita Iyer, Process Engineer", "All zones", "Design and operating calculations", "engineering calculation review assumptions units signoff", "Calculations identify purpose, inputs, units, assumptions, method, result, sensitivity, reviewer, and revision. Independent review checks unit consistency, source data, boundary conditions, and applicability. A calculation output is not an operating limit until approved through the engineering and MOC process."),
    _r("governance", "Temporary repair control", "Mohan Iyer, Reliability Engineer", "All zones", "Temporary clamps and repairs", "temporary repair clamp expiry inspection integrity", "Temporary repairs receive an engineered basis, risk assessment, inspection interval, owner, expiry date, replacement plan, and visible identification. Operators report leakage or change immediately. An expired temporary repair cannot remain by informal agreement; it requires escalation and a permanent solution."),
    _r("governance", "Management review of open actions", "Meera Joshi, HSE Manager", "All zones", "Action tracking system", "action register overdue owner closure evidence", "Managers review overdue actions by risk, barrier impact, age, and dependency. Extensions require justification and accountable approval. Closure includes objective evidence and an effectiveness check; changing a status to complete without evidence is not acceptable."),
    _r("governance", "Business continuity for control room", "Sanjay Kulkarni, Operations Superintendent", "All zones", "Control room continuity", "business continuity control room backup communication", "The continuity plan covers control-room loss, power loss, communication failure, historian outage, staffing shortage, and restricted access. Operators use approved backups and paper logs when necessary, then reconcile records after recovery. Safety functions and emergency communication take priority over data completeness."),
]

# One organisation with hundreds of distinct references. Each edition keeps
# the same subject useful for retrieval but changes the audience and operating
# focus, so the corpus is broad rather than 300 identical copies.
_BASE_RECORDS = RECORDS[:100]
_EDITIONS = (
    ("Field execution", "field operators, local checks, and shift records"),
    ("Supervisor control", "supervisors, handover, escalation, and verification"),
    ("Reliability review", "engineering trends, recurring risk, and action closure"),
)
RECORDS = []
for _edition, _focus in _EDITIONS:
    for _rec in _BASE_RECORDS:
        RECORDS.append(Record(
            category=_rec.category,
            title=f"{_rec.title} - {_edition}",
            owner=_rec.owner,
            zone=_rec.zone,
            asset=_rec.asset,
            keywords=f"{_rec.keywords} {_edition.lower()}",
            details=(f"This {_edition.lower()} reference emphasizes {_focus}. "
                     f"{_rec.details}"),
        ))


def _document_text(rec, number):
    """Expand a compact record into a substantial, retrievable procedure note."""
    return f"""{TITLE_PREFIX} DOCUMENT {number:03d}

Document title: {rec.title}
Category: {rec.category}
Area or zone: {rec.zone}
Primary owner: {rec.owner}
Asset or scope: {rec.asset}
Search terms: {rec.keywords}
Document status: Synthetic demonstration reference; use current approved site procedure for real work.
Revision: DEMO-1 | Effective date: 2026-01-15 | Review date: 2027-01-15

1. Purpose and applicability
This controlled-style reference explains the expected operating context for {rec.title}. It applies to {rec.zone} and the scope identified as {rec.asset}. It is written for operators, supervisors, maintenance personnel, engineers, HSE staff, laboratory staff, and managers who need a common picture of the work. The document is synthetic demonstration data for BigBrain retrieval and must not be used as authorization to operate equipment, change a setpoint, defeat a safeguard, or enter a hazardous area.

2. Operating context
{rec.details}

The accountable owner is {rec.owner}. The owner coordinates with the control room, affected Area Manager, Maintenance, Instrumentation, Laboratory, HSE, and any receiving or supplying zone. The first response to an abnormal condition is to protect people, prevent escalation, stabilize the process, and communicate an accurate status. Production targets never override an isolation, permit, alarm response, quality hold, or emergency instruction.

3. Required records and checks
Before work or operation, confirm the current revision, equipment identity, approved line-up, operating window, permit status where relevant, isolation status, instrument health, communication channel, and emergency route. Record the time, person, equipment tag, observed value, unit, action, and result. When a reading is entered, retain the original observation and timestamp. If the observation is uncertain, mark it for verification rather than filling a plausible value. Attach photographs, certificates, laboratory results, drawings, or work-order evidence when those records are part of the activity.

4. Interfaces and escalation
The control room is notified before a change that can affect another zone, tank movement, pipeline route, utility demand, product quality, flare load, discharge, or emergency response. Escalate immediately for loss of containment, unexpected pressure or temperature, failed protection, wrong line-up, missing personnel, unsafe atmosphere, fire, injury, environmental release, or data that could lead to an unsafe decision. The Shift Supervisor decides whether to hold rate, stop transfer, isolate, depressurize, evacuate, or request the Incident Commander. The owner records the decision and follow-up action.

5. Verification questions
When using this document, staff should be able to answer: What zone and asset are involved? Who owns the activity? What is the approved operating or safety boundary? Which value or condition must be checked? What is the immediate stop condition? Who must be informed? Which record proves completion? What is the next review or inspection date? These questions are intentionally included so BigBrain can retrieve useful context for operators with different technical backgrounds.

6. Synthetic demo note
This document belongs to the fictional Indian Oil Demo Operations organisation and is one of 100 synthetic references created for local RAG demonstrations. Names, tags, limits, intervals, contacts, and dates are invented for testing. A real industrial deployment must replace this reference with approved, site-specific documents and enforce the organization's authorization, permit, alarm, quality, and records systems.
"""


def _reset_seed_docs(org_id):
    conn = get_conn()
    cur = conn.cursor()
    cur.execute(
        "DELETE FROM documents WHERE org_id=%s AND title LIKE %s RETURNING id;",
        (org_id, TITLE_PREFIX + "%"),
    )
    deleted = len(cur.fetchall())
    conn.commit()
    cur.close()
    conn.close()
    return deleted


def _ensure_org(org_id):
    conn = get_conn()
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO orgs (id, name) VALUES (%s,%s) "
        "ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name;",
        (org_id, ORG_NAME),
    )
    conn.commit()
    cur.close()
    conn.close()


def _existing_seed_titles(org_id):
    conn = get_conn()
    cur = conn.cursor()
    cur.execute(
        "SELECT title FROM documents WHERE org_id=%s AND title LIKE %s;",
        (org_id, TITLE_PREFIX + "%"),
    )
    titles = {r[0] for r in cur.fetchall()}
    cur.close()
    conn.close()
    return titles


def backfill_vectors(org_id="indianoil-demo", batch_size=64):
    """Embed any remaining leaf chunks for this org after an interrupted run."""
    from data.embeddings import embed_texts
    total = 0
    while True:
        conn = get_conn()
        cur = conn.cursor()
        cur.execute(
            """SELECT id, content FROM chunks
               WHERE org_id=%s AND embedding IS NULL
                 AND (chunk_level IS NULL OR chunk_level='leaf')
               ORDER BY id LIMIT %s;""",
            (org_id, batch_size),
        )
        rows = cur.fetchall()
        if not rows:
            cur.close()
            conn.close()
            break
        try:
            vecs = embed_texts([r[1] for r in rows])
            for (chunk_id, _), vec in zip(rows, vecs):
                cur.execute("UPDATE chunks SET embedding=%s::vector WHERE id=%s;", (vec, chunk_id))
            conn.commit()
            total += len(rows)
            print(f"  backfilled {total} vectors", flush=True)
        finally:
            cur.close()
            conn.close()
    return total


def seed(org_id="indianoil-demo", reset=True, resume=False, backfill=True):
    if len(RECORDS) != 300:
        raise RuntimeError(f"seed catalog must contain exactly 300 records, found {len(RECORDS)}")
    _ensure_org(org_id)
    if reset:
        print(f"removed {_reset_seed_docs(org_id)} previous synthetic documents")
    existing = _existing_seed_titles(org_id) if resume else set()
    todo = [r for r in RECORDS if f"{TITLE_PREFIX} {r.title}" not in existing]
    print(f"ingesting {len(todo)} of {len(RECORDS)} synthetic oil-operations documents into org {org_id}", flush=True)
    ids = []
    for number, rec in enumerate(todo, start=1):
        title = f"{TITLE_PREFIX} {rec.title}"
        doc_id = ingest_doc(
            title=title,
            content=_document_text(rec, number),
            org_id=org_id,
            dept="operations",
            doc_class="open",
        )
        ids.append(doc_id)
        if number % 10 == 0 or number == len(RECORDS):
            print(f"  ingested {number:03d}/{len(todo)} (last document id {doc_id})", flush=True)
    if backfill:
        print("checking for unembedded leaf chunks", flush=True)
        backfill_vectors(org_id)
    print(f"seed complete: {len(todo)} documents processed; org={org_id}", flush=True)
    return ids


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Seed synthetic oil operations RAG data")
    parser.add_argument("--org-id", default="indianoil-demo")
    parser.add_argument("--no-reset", action="store_true", help="keep prior synthetic docs (creates duplicates)")
    parser.add_argument("--resume", action="store_true", help="continue an interrupted seed without duplicating documents")
    parser.add_argument("--no-backfill", action="store_true", help="skip embedding repair after ingest")
    args = parser.parse_args()
    seed(args.org_id, reset=not args.no_reset and not args.resume,
         resume=args.resume, backfill=not args.no_backfill)
